function init(self)
	msg.post('#sprite', 'disable')
end

function on_message(self, message_id, message, sender)
	if message_id == hash('end_game') then
        timer.delay(
            math.random(1, 3),
            false,
            function (self, handle, time_elapsed)
                msg.post('#sprite', 'enable')
        		msg.post('#sprite', 'play_animation', {id = hash('endless')})
            end
        )
    end
end
